[Kaufland]
url = 'https://filiale.kaufland.de/angebote/aktuelle-woche.html'

[Edeka]
url = 'https://www.edeka.de/eh/s%C3%BCdbayern/edeka-spitt-erdinger-stra%C3%9Fe-26-28/angebote.jsp'

[Aldi_Sued]
url = 'https://www.aldi-sued.de/de/angebote.html'